// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "4f331be3-4ad4-4da9-9f14-5ba29927102f");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1737821025);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1737821024);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{18357413-f735-4c37-8e79-d6ace276dc79}");
user_pref("browser.discovery.enabled", false);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1737820958);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 150);
user_pref("browser.newtabpage.activity-stream.impressionId", "{1347f8de-a875-4591-869c-4560da1b213a}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1737820960);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1737821024869");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1737842624869");
user_pref("browser.search.region", "BY");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20250121220303");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20250121220303");
user_pref("browser.startup.homepage_override.mstone", "134.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1737822325);
user_pref("browser.toolbars.bookmarks.visibility", "never");
user_pref("browser.topsites.contile.lastFetch", 1737821080);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"save-to-pocket-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.dau.cachedUsageProfileID", "beefbeef-beef-beef-beef-beeefbeefbee");
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1737821023415");
user_pref("distribution.iniFile.exists.appversion", "134.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "BY");
user_pref("dom.push.userAgentID", "69e09669cc5f4765842f7da508becc5c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20250121220303");
user_pref("extensions.lastAppVersion", "134.0.2");
user_pref("extensions.lastPlatformVersion", "134.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"858b0c16-97b6-4ed8-8dd8-84e5dfaee2be\",\"pictureinpicture@mozilla.org\":\"c39a7420-e210-4aad-aa5e-868a3c56fabd\",\"screenshots@mozilla.org\":\"90ad0ca3-abd1-4e2f-b300-ffee2cd34081\",\"webcompat-reporter@mozilla.org\":\"c4b468e4-cc70-4cac-b2d1-51d4c621f7f9\",\"webcompat@mozilla.org\":\"4055b769-9989-4508-969e-d3f2050272f3\",\"default-theme@mozilla.org\":\"5d2c1c77-6b76-44d4-8fec-6f4f1248a218\",\"addons-search-detection@mozilla.com\":\"97ca60d4-230f-4835-ac64-e90e08211d4b\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastFaviconsCorruptionInDaysFromEpoch", 20113);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs2", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("sidebar.backupState", "{\"width\":\"\",\"command\":\"\"}");
user_pref("toolkit.startup.last_success", 1737822317);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.cachedProfileGroupID", "decafdec-afde-cafd-ecaf-decafdecafde");
user_pref("toolkit.telemetry.previousBuildID", "20250121220303");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
